package com.cloudofficeprint.Examples.BeginersGuide;

import com.cloudofficeprint.Mimetype;
import com.cloudofficeprint.Output.Output;
import com.cloudofficeprint.PrintJob;
import com.cloudofficeprint.RenderElements.*;
import com.cloudofficeprint.RenderElements.Loops.InlineDataLoop;
import com.cloudofficeprint.Resources.Base64Resource;
import com.cloudofficeprint.Response;
import com.cloudofficeprint.Server.Server;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Hashtable;

public class UsingTOC {
    public void main() throws Exception {
        System.out.println("I am in UsingTOC example");
        // Load template
        Base64Resource template = new Base64Resource();
        InputStream resourceAsStream = getClass().getResourceAsStream("/BeginnerGuide/UsingTOC/toc_temp.docx");
        byte[] targetArray = new byte[resourceAsStream.available()];
        resourceAsStream.read(targetArray);
        String encodedString = Base64.getEncoder().encodeToString(targetArray);
        template.setFileBase64(encodedString);
        template.setFiletype("docx");
        template.setMimeType(Mimetype.getMimeType("docx"));

        //Set Cloud office Print server
        Server copServer = new Server("http://localhost:8010/");
        copServer.setVerbose(true);
        copServer.setAPIKey("YOUR_API_KEY");
        // Create main element collection
        // Create main element collection
        ElementCollection data = new ElementCollection("data");

        // Add Table of Contents
        TableOfContents toc = new TableOfContents("toc_demo", "Table of Contents - Generated by AOP", 2, "hyphen");
        data.addElement(toc);

        // Create customers array
        ArrayList<RenderElement> customersList = new ArrayList<>();

        // Customer data in array
        Object[][] customersData = {
                {"John", "Dulles", "Sterling", "45020 Aviation Drive", null, "VA", "john.dulles@email.com", "703-555-2143", "703-555-8967", "http://www.johndulles.com"},
                {"Fiorello", "LaGuardia", "Flushing", "Hangar Center", "Third Floor", "NY", null, "212-555-3923", null, null},
                {"Albert", "Lambert", "St. Louis", "10701 Lambert International Blvd.", null, "MO", null, "314-555-4022", null, null}
        };

        // Create collections for each customer
        for (Object[] customer : customersData) {
            ElementCollection custCollection = new ElementCollection("customer");
            custCollection.addElement(new Property("cust_f_name", customer[0].toString()));
            custCollection.addElement(new Property("cust_l_name", customer[1].toString()));
            custCollection.addElement(new Property("city", customer[2].toString()));
            custCollection.addElement(new Property("addr_1", customer[3].toString()));
            if (customer[4] != null) custCollection.addElement(new Property("addr_2", customer[4].toString()));
            custCollection.addElement(new Property("state", customer[5].toString()));
            if (customer[6] != null) custCollection.addElement(new Property("email", customer[6].toString()));
            custCollection.addElement(new Property("phone_number_1", customer[7].toString()));
            if (customer[8] != null) custCollection.addElement(new Property("phone_number_2", customer[8].toString()));
            if (customer[9] != null) custCollection.addElement(new Property("url", customer[9].toString()));
            customersList.add(custCollection);
        }

        // Create loop for customers
        InlineDataLoop customersLoop = new InlineDataLoop("cust_list", customersList);
        data.addElement(customersLoop);

        //HTML content
        String htmlContent = "<h1>Heading 1 from html</h1>\n" +
                "<h2>Heading 2 from html</h2>\n" +
                "<h3>Heading 3 from html</h3>\n" +
                "AOP also handles the headings from html";

        HTML html = new HTML("sample_html", htmlContent);
        data.addElement(html);

        Output conf = new Output("docx", "raw", "libreoffice", null, null, null, null);
        Hashtable<String, RenderElement> dataTable = new Hashtable<String, RenderElement>();
        dataTable.put("data", data);
        PrintJob printJob = new PrintJob(dataTable, copServer, conf, template, null, null, null, null);
        Response response = printJob.execute();

        // Save the response to a file
        response.downloadLocally("./downloads/BeginnerGuide/UsingTOC/output");
    }
}
